// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/post.proto

package ppb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type PostResponseList struct {
	Posts                []*PostResponse `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PostResponseList) Reset()         { *m = PostResponseList{} }
func (m *PostResponseList) String() string { return proto.CompactTextString(m) }
func (*PostResponseList) ProtoMessage()    {}
func (*PostResponseList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{1}
}

func (m *PostResponseList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponseList.Unmarshal(m, b)
}
func (m *PostResponseList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponseList.Marshal(b, m, deterministic)
}
func (m *PostResponseList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponseList.Merge(m, src)
}
func (m *PostResponseList) XXX_Size() int {
	return xxx_messageInfo_PostResponseList.Size(m)
}
func (m *PostResponseList) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponseList.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponseList proto.InternalMessageInfo

func (m *PostResponseList) GetPosts() []*PostResponse {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Page struct {
	PageNumber           uint32   `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize             uint32   `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{2}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageNumber() uint32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *Page) GetPageSize() uint32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ID struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{3}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type PostResponse struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{4}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PostResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PostResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

type UpdateRequest struct {
	ID                   uint32   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{5}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetID() uint32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "post.Empty")
	proto.RegisterType((*PostResponseList)(nil), "post.PostResponseList")
	proto.RegisterType((*Page)(nil), "post.Page")
	proto.RegisterType((*ID)(nil), "post.ID")
	proto.RegisterType((*PostResponse)(nil), "post.PostResponse")
	proto.RegisterType((*UpdateRequest)(nil), "post.UpdateRequest")
}

func init() {
	proto.RegisterFile("proto/post.proto", fileDescriptor_5e57bba97c118b83)
}

var fileDescriptor_5e57bba97c118b83 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0x4f, 0x6b, 0xc2, 0x40,
	0x10, 0xc5, 0x4d, 0x4c, 0xfc, 0x33, 0xa9, 0x22, 0x53, 0x69, 0x83, 0x3d, 0x54, 0x16, 0x0a, 0xb9,
	0x54, 0xc1, 0x5e, 0x7b, 0x92, 0x94, 0x12, 0x28, 0x45, 0x22, 0xbd, 0xf4, 0x22, 0x49, 0x33, 0x48,
	0x40, 0xcd, 0x36, 0xbb, 0x16, 0xf4, 0x13, 0xf6, 0x63, 0x95, 0xdd, 0x95, 0x9a, 0x5a, 0x2f, 0x61,
	0xf6, 0xcd, 0x6f, 0xdf, 0xbe, 0xcc, 0x2e, 0xf4, 0x78, 0x59, 0xc8, 0x62, 0xcc, 0x0b, 0x21, 0x47,
	0xba, 0x44, 0x47, 0xd5, 0xac, 0x09, 0xee, 0xd3, 0x9a, 0xcb, 0x1d, 0x7b, 0x84, 0xde, 0xac, 0x10,
	0x32, 0x26, 0xc1, 0x8b, 0x8d, 0xa0, 0x97, 0x5c, 0x48, 0x0c, 0xc0, 0x55, 0x90, 0xf0, 0xad, 0x61,
	0x3d, 0xf0, 0x26, 0x38, 0xd2, 0xdb, 0xab, 0x58, 0x6c, 0x00, 0x16, 0x82, 0x33, 0x4b, 0x96, 0x84,
	0xb7, 0xe0, 0xf1, 0x64, 0x49, 0x8b, 0xcd, 0x76, 0x9d, 0x52, 0xe9, 0x5b, 0x43, 0x2b, 0xe8, 0xc4,
	0xa0, 0xa4, 0x57, 0xad, 0xe0, 0x0d, 0xb4, 0x35, 0x20, 0xf2, 0x3d, 0xf9, 0xb6, 0x6e, 0xb7, 0x94,
	0x30, 0xcf, 0xf7, 0xc4, 0xfa, 0x60, 0x47, 0x21, 0x76, 0xd5, 0xf7, 0xb0, 0xd5, 0x8e, 0x42, 0x96,
	0xc0, 0x45, 0xf5, 0xc8, 0x4a, 0xdf, 0x55, 0x7d, 0xbc, 0x86, 0xe6, 0x56, 0x50, 0xb9, 0xc8, 0x33,
	0x6d, 0xe8, 0xc6, 0x0d, 0xb5, 0x8c, 0x32, 0xec, 0x83, 0x2b, 0x73, 0xb9, 0x22, 0xbf, 0x3e, 0xb4,
	0x82, 0x76, 0x6c, 0x16, 0x88, 0xe0, 0xa4, 0x45, 0xb6, 0xf3, 0x1d, 0x2d, 0xea, 0x9a, 0x45, 0xd0,
	0x79, 0xe3, 0x59, 0x22, 0x29, 0xa6, 0xcf, 0x2d, 0x09, 0x79, 0x9a, 0xe1, 0x68, 0x65, 0x9f, 0xb3,
	0xaa, 0x1f, 0xad, 0x26, 0xdf, 0x16, 0x78, 0x2a, 0xee, 0x9c, 0xca, 0xaf, 0xfc, 0x83, 0xf0, 0x1e,
	0xbc, 0x67, 0x92, 0x4a, 0x99, 0xee, 0xa2, 0x10, 0x5b, 0x66, 0x86, 0x51, 0x38, 0x38, 0x33, 0x4d,
	0x56, 0xc3, 0x31, 0x34, 0x15, 0xae, 0x66, 0x09, 0x07, 0x20, 0x59, 0xd2, 0xe0, 0xea, 0x3f, 0xac,
	0x6e, 0x88, 0xd5, 0x70, 0x02, 0x5d, 0x13, 0xfd, 0xf7, 0x88, 0x4b, 0xc3, 0xfe, 0xf9, 0xa1, 0x81,
	0x67, 0x44, 0x7d, 0xd7, 0x78, 0x07, 0x10, 0xd2, 0x8a, 0x24, 0x9d, 0x44, 0xaa, 0x42, 0xac, 0x36,
	0x6d, 0xbc, 0x3b, 0x63, 0xce, 0xd3, 0xb4, 0xa1, 0x1f, 0xcc, 0xc3, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x1c, 0x13, 0x0d, 0x7a, 0x44, 0x02, 0x00, 0x00,
}
