// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/post.proto

package ppb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PostResponseList struct {
	Posts                []*PostResponse `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PostResponseList) Reset()         { *m = PostResponseList{} }
func (m *PostResponseList) String() string { return proto.CompactTextString(m) }
func (*PostResponseList) ProtoMessage()    {}
func (*PostResponseList) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{0}
}

func (m *PostResponseList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponseList.Unmarshal(m, b)
}
func (m *PostResponseList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponseList.Marshal(b, m, deterministic)
}
func (m *PostResponseList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponseList.Merge(m, src)
}
func (m *PostResponseList) XXX_Size() int {
	return xxx_messageInfo_PostResponseList.Size(m)
}
func (m *PostResponseList) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponseList.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponseList proto.InternalMessageInfo

func (m *PostResponseList) GetPosts() []*PostResponse {
	if m != nil {
		return m.Posts
	}
	return nil
}

type Page struct {
	PageNumber           int32    `protobuf:"varint,1,opt,name=page_number,json=pageNumber,proto3" json:"page_number,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{1}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageNumber() int32 {
	if m != nil {
		return m.PageNumber
	}
	return 0
}

func (m *Page) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ID struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ID) Reset()         { *m = ID{} }
func (m *ID) String() string { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()    {}
func (*ID) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{2}
}

func (m *ID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ID.Unmarshal(m, b)
}
func (m *ID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ID.Marshal(b, m, deterministic)
}
func (m *ID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ID.Merge(m, src)
}
func (m *ID) XXX_Size() int {
	return xxx_messageInfo_ID.Size(m)
}
func (m *ID) XXX_DiscardUnknown() {
	xxx_messageInfo_ID.DiscardUnknown(m)
}

var xxx_messageInfo_ID proto.InternalMessageInfo

func (m *ID) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

type PostResponse struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PostResponse) Reset()         { *m = PostResponse{} }
func (m *PostResponse) String() string { return proto.CompactTextString(m) }
func (*PostResponse) ProtoMessage()    {}
func (*PostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e57bba97c118b83, []int{3}
}

func (m *PostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PostResponse.Unmarshal(m, b)
}
func (m *PostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PostResponse.Marshal(b, m, deterministic)
}
func (m *PostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PostResponse.Merge(m, src)
}
func (m *PostResponse) XXX_Size() int {
	return xxx_messageInfo_PostResponse.Size(m)
}
func (m *PostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PostResponse proto.InternalMessageInfo

func (m *PostResponse) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *PostResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *PostResponse) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PostResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*PostResponseList)(nil), "post.PostResponseList")
	proto.RegisterType((*Page)(nil), "post.Page")
	proto.RegisterType((*ID)(nil), "post.ID")
	proto.RegisterType((*PostResponse)(nil), "post.PostResponse")
}

func init() {
	proto.RegisterFile("proto/post.proto", fileDescriptor_5e57bba97c118b83)
}

var fileDescriptor_5e57bba97c118b83 = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x6b, 0xc2, 0x40,
	0x10, 0x85, 0x8d, 0xc6, 0xa8, 0x93, 0x52, 0x64, 0x90, 0x36, 0xd8, 0x43, 0xc3, 0x9e, 0x72, 0xa9,
	0x01, 0x7b, 0xed, 0x49, 0x02, 0x25, 0x50, 0x8a, 0xc4, 0x5b, 0x2f, 0x92, 0x34, 0x43, 0x58, 0xa8,
	0xee, 0x92, 0x5d, 0x0b, 0xfa, 0xeb, 0xcb, 0x6c, 0x72, 0x90, 0xb6, 0x97, 0xf0, 0xe6, 0xbd, 0x6f,
	0x32, 0xcc, 0x2c, 0xcc, 0x75, 0xab, 0xac, 0x4a, 0xb5, 0x32, 0x76, 0xe5, 0x24, 0xfa, 0xac, 0xc5,
	0x0b, 0xcc, 0xb7, 0xca, 0xd8, 0x82, 0x8c, 0x56, 0x47, 0x43, 0x6f, 0xd2, 0x58, 0x4c, 0x60, 0xcc,
	0x99, 0x89, 0xbc, 0x78, 0x94, 0x84, 0x6b, 0x5c, 0xb9, 0xae, 0x6b, 0xac, 0xe8, 0x00, 0x91, 0x81,
	0xbf, 0x2d, 0x1b, 0xc2, 0x47, 0x08, 0x75, 0xd9, 0xd0, 0xfe, 0x78, 0x3a, 0x54, 0xd4, 0x46, 0x5e,
	0xec, 0x25, 0xe3, 0x02, 0xd8, 0x7a, 0x77, 0x0e, 0x3e, 0xc0, 0xcc, 0x01, 0x46, 0x5e, 0x28, 0x1a,
	0xba, 0x78, 0xca, 0xc6, 0x4e, 0x5e, 0x48, 0x2c, 0x60, 0x98, 0x67, 0x78, 0xcb, 0xdf, 0xbe, 0x75,
	0x98, 0x67, 0xa2, 0x84, 0x9b, 0xeb, 0x91, 0xbf, 0x73, 0xbc, 0x87, 0xc9, 0xc9, 0x50, 0xbb, 0x97,
	0x75, 0xff, 0xc3, 0x80, 0xcb, 0xbc, 0xc6, 0x05, 0x8c, 0xad, 0xb4, 0x5f, 0x14, 0x8d, 0x62, 0x2f,
	0x99, 0x15, 0x5d, 0x81, 0x08, 0x7e, 0xa5, 0xea, 0x73, 0xe4, 0x3b, 0xd3, 0xe9, 0xf5, 0x01, 0x42,
	0x1e, 0xb1, 0xa3, 0xf6, 0x5b, 0x7e, 0x12, 0x3e, 0x41, 0xf8, 0x4a, 0x96, 0x9d, 0xcd, 0x39, 0xcf,
	0x70, 0xda, 0xed, 0x9d, 0x67, 0xcb, 0x7f, 0x2e, 0x20, 0x06, 0x98, 0xc2, 0x84, 0x71, 0xde, 0x1f,
	0x7a, 0xa0, 0x6c, 0x68, 0x79, 0xf7, 0x17, 0xe6, 0xab, 0x8a, 0xc1, 0x26, 0xf8, 0xf0, 0x53, 0xad,
	0xab, 0x2a, 0x70, 0x0f, 0xf0, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0x33, 0x87, 0xba, 0xfc, 0x94,
	0x01, 0x00, 0x00,
}
