// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/collector.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CollectPostsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectPostsResponse) Reset()         { *m = CollectPostsResponse{} }
func (m *CollectPostsResponse) String() string { return proto.CompactTextString(m) }
func (*CollectPostsResponse) ProtoMessage()    {}
func (*CollectPostsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8cf59175f5ed68a, []int{0}
}

func (m *CollectPostsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectPostsResponse.Unmarshal(m, b)
}
func (m *CollectPostsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectPostsResponse.Marshal(b, m, deterministic)
}
func (m *CollectPostsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectPostsResponse.Merge(m, src)
}
func (m *CollectPostsResponse) XXX_Size() int {
	return xxx_messageInfo_CollectPostsResponse.Size(m)
}
func (m *CollectPostsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectPostsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectPostsResponse proto.InternalMessageInfo

type CollectPostsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectPostsRequest) Reset()         { *m = CollectPostsRequest{} }
func (m *CollectPostsRequest) String() string { return proto.CompactTextString(m) }
func (*CollectPostsRequest) ProtoMessage()    {}
func (*CollectPostsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f8cf59175f5ed68a, []int{1}
}

func (m *CollectPostsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectPostsRequest.Unmarshal(m, b)
}
func (m *CollectPostsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectPostsRequest.Marshal(b, m, deterministic)
}
func (m *CollectPostsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectPostsRequest.Merge(m, src)
}
func (m *CollectPostsRequest) XXX_Size() int {
	return xxx_messageInfo_CollectPostsRequest.Size(m)
}
func (m *CollectPostsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectPostsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectPostsRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CollectPostsResponse)(nil), "post.CollectPostsResponse")
	proto.RegisterType((*CollectPostsRequest)(nil), "post.CollectPostsRequest")
}

func init() {
	proto.RegisterFile("proto/collector.proto", fileDescriptor_f8cf59175f5ed68a)
}

var fileDescriptor_f8cf59175f5ed68a = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xc9, 0x49, 0x4d, 0x2e, 0xc9, 0x2f, 0xd2, 0x03, 0xf3, 0x85, 0x58,
	0x0a, 0xf2, 0x8b, 0x4b, 0x94, 0xc4, 0xb8, 0x44, 0x9c, 0x21, 0x12, 0x01, 0xf9, 0xc5, 0x25, 0xc5,
	0x41, 0xa9, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x4a, 0xa2, 0x5c, 0xc2, 0xa8, 0xe2, 0x85, 0xa5,
	0xa9, 0xc5, 0x25, 0x46, 0xd1, 0x5c, 0x02, 0xce, 0x30, 0x73, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93,
	0x53, 0x85, 0xdc, 0xb9, 0x78, 0x90, 0x95, 0x0a, 0x49, 0xea, 0x81, 0x4c, 0xd6, 0xc3, 0xa2, 0x5d,
	0x4a, 0x0a, 0x9b, 0x14, 0xd4, 0x46, 0x06, 0x27, 0xd6, 0x28, 0x66, 0xfd, 0x82, 0xa4, 0x24, 0x36,
	0xb0, 0xfb, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x80, 0x67, 0x08, 0xeb, 0xb8, 0x00, 0x00,
	0x00,
}
